# Generated by Django 3.0.3 on 2020-03-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('job', models.CharField(max_length=30, null=True)),
                ('belogns_to', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'name',
            },
        ),
    ]
