# Generated by Django 3.0.3 on 2020-03-03 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Team'},
        ),
        migrations.AddField(
            model_name='fort',
            name='date_filled',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
