# Generated by Django 3.0.3 on 2020-03-05 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortScreenShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc1', models.ImageField(null=True, upload_to='app/images')),
                ('sc2', models.ImageField(null=True, upload_to='app/images')),
                ('sc3', models.ImageField(null=True, upload_to='app/images')),
                ('sc4', models.ImageField(null=True, upload_to='app/images')),
                ('sc5', models.ImageField(null=True, upload_to='app/images')),
                ('sc6', models.ImageField(null=True, upload_to='app/images')),
                ('fort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Fort')),
            ],
            options={
                'verbose_name': 'Screenshot',
                'verbose_name_plural': 'Screenshots',
            },
        ),
    ]
