# Generated by Django 3.0.3 on 2020-03-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_fortscreenshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='fort',
            name='sc1',
            field=models.ImageField(null=True, upload_to='app/images'),
        ),
        migrations.AddField(
            model_name='fort',
            name='sc2',
            field=models.ImageField(null=True, upload_to='app/images'),
        ),
        migrations.AddField(
            model_name='fort',
            name='sc3',
            field=models.ImageField(null=True, upload_to='app/images'),
        ),
        migrations.AddField(
            model_name='fort',
            name='sc4',
            field=models.ImageField(null=True, upload_to='app/images'),
        ),
        migrations.AddField(
            model_name='fort',
            name='sc5',
            field=models.ImageField(null=True, upload_to='app/images'),
        ),
        migrations.AddField(
            model_name='fort',
            name='sc6',
            field=models.ImageField(null=True, upload_to='app/images'),
        ),
    ]
