# Generated by Django 3.0.3 on 2020-03-05 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200306_0037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FortScreenShots',
        ),
    ]
