# Generated by Django 3.0.3 on 2020-03-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_fortscreenshots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fort',
            name='sc4',
        ),
        migrations.RemoveField(
            model_name='fort',
            name='sc5',
        ),
        migrations.RemoveField(
            model_name='fort',
            name='sc6',
        ),
    ]
